// Code generated by protoc-gen-go. DO NOT EDIT.
// source: copyrightDemo.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	UserPhone            uint64   `protobuf:"varint,1,opt,name=userPhone,proto3" json:"userPhone,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a10b2d58ee7f8f, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserPhone() uint64 {
	if m != nil {
		return m.UserPhone
	}
	return 0
}

func (m *CreateUserRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type CreateUserResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a10b2d58ee7f8f, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type ConfirmRequest struct {
	UserPhone            uint64   `protobuf:"varint,1,opt,name=userPhone,proto3" json:"userPhone,omitempty"`
	Tag                  uint64   `protobuf:"varint,2,opt,name=tag,proto3" json:"tag,omitempty"`
	ImgName              string   `protobuf:"bytes,3,opt,name=imgName,proto3" json:"imgName,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmRequest) Reset()         { *m = ConfirmRequest{} }
func (m *ConfirmRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmRequest) ProtoMessage()    {}
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a10b2d58ee7f8f, []int{2}
}

func (m *ConfirmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmRequest.Unmarshal(m, b)
}
func (m *ConfirmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmRequest.Merge(m, src)
}
func (m *ConfirmRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmRequest.Size(m)
}
func (m *ConfirmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmRequest proto.InternalMessageInfo

func (m *ConfirmRequest) GetUserPhone() uint64 {
	if m != nil {
		return m.UserPhone
	}
	return 0
}

func (m *ConfirmRequest) GetTag() uint64 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *ConfirmRequest) GetImgName() string {
	if m != nil {
		return m.ImgName
	}
	return ""
}

func (m *ConfirmRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ConfirmResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmResponse) Reset()         { *m = ConfirmResponse{} }
func (m *ConfirmResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmResponse) ProtoMessage()    {}
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a10b2d58ee7f8f, []int{3}
}

func (m *ConfirmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmResponse.Unmarshal(m, b)
}
func (m *ConfirmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmResponse.Merge(m, src)
}
func (m *ConfirmResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmResponse.Size(m)
}
func (m *ConfirmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmResponse proto.InternalMessageInfo

func (m *ConfirmResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type TradeRequest struct {
	PurchasePhone        uint64   `protobuf:"varint,1,opt,name=purchasePhone,proto3" json:"purchasePhone,omitempty"`
	SellerPhone          uint64   `protobuf:"varint,2,opt,name=sellerPhone,proto3" json:"sellerPhone,omitempty"`
	Price                uint64   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Tag                  uint64   `protobuf:"varint,4,opt,name=tag,proto3" json:"tag,omitempty"`
	ImgName              string   `protobuf:"bytes,5,opt,name=imgName,proto3" json:"imgName,omitempty"`
	Key                  string   `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeRequest) Reset()         { *m = TradeRequest{} }
func (m *TradeRequest) String() string { return proto.CompactTextString(m) }
func (*TradeRequest) ProtoMessage()    {}
func (*TradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a10b2d58ee7f8f, []int{4}
}

func (m *TradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRequest.Unmarshal(m, b)
}
func (m *TradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRequest.Marshal(b, m, deterministic)
}
func (m *TradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRequest.Merge(m, src)
}
func (m *TradeRequest) XXX_Size() int {
	return xxx_messageInfo_TradeRequest.Size(m)
}
func (m *TradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRequest proto.InternalMessageInfo

func (m *TradeRequest) GetPurchasePhone() uint64 {
	if m != nil {
		return m.PurchasePhone
	}
	return 0
}

func (m *TradeRequest) GetSellerPhone() uint64 {
	if m != nil {
		return m.SellerPhone
	}
	return 0
}

func (m *TradeRequest) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeRequest) GetTag() uint64 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *TradeRequest) GetImgName() string {
	if m != nil {
		return m.ImgName
	}
	return ""
}

func (m *TradeRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type TradeResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeResponse) Reset()         { *m = TradeResponse{} }
func (m *TradeResponse) String() string { return proto.CompactTextString(m) }
func (*TradeResponse) ProtoMessage()    {}
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6a10b2d58ee7f8f, []int{5}
}

func (m *TradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeResponse.Unmarshal(m, b)
}
func (m *TradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeResponse.Marshal(b, m, deterministic)
}
func (m *TradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeResponse.Merge(m, src)
}
func (m *TradeResponse) XXX_Size() int {
	return xxx_messageInfo_TradeResponse.Size(m)
}
func (m *TradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TradeResponse proto.InternalMessageInfo

func (m *TradeResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "proto.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "proto.CreateUserResponse")
	proto.RegisterType((*ConfirmRequest)(nil), "proto.ConfirmRequest")
	proto.RegisterType((*ConfirmResponse)(nil), "proto.ConfirmResponse")
	proto.RegisterType((*TradeRequest)(nil), "proto.TradeRequest")
	proto.RegisterType((*TradeResponse)(nil), "proto.TradeResponse")
}

func init() {
	proto.RegisterFile("copyrightDemo.proto", fileDescriptor_c6a10b2d58ee7f8f)
}

var fileDescriptor_c6a10b2d58ee7f8f = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xb5, 0x52, 0x50, 0x06, 0x41, 0x5d, 0x90, 0xac, 0xc4, 0x03, 0x69, 0x4c, 0xc4, 0xc4, 0x70,
	0xc0, 0x8b, 0x27, 0x2f, 0x48, 0x3c, 0x69, 0xcc, 0x46, 0x0f, 0x1e, 0x57, 0x18, 0xa1, 0xb1, 0x65,
	0xeb, 0xee, 0xf6, 0xc0, 0x2f, 0xf9, 0x95, 0xa6, 0xdb, 0x2e, 0xb4, 0xd2, 0xa8, 0xa7, 0xce, 0x7b,
	0xed, 0xbc, 0x79, 0xaf, 0x33, 0xd0, 0x9e, 0x8a, 0x68, 0x25, 0xfd, 0xf9, 0x42, 0xdf, 0x61, 0x28,
	0x86, 0x91, 0x14, 0x5a, 0x90, 0xaa, 0x79, 0x78, 0x13, 0x38, 0x1e, 0x4b, 0xe4, 0x1a, 0x5f, 0x14,
	0x4a, 0x86, 0x9f, 0x31, 0x2a, 0x4d, 0xce, 0xa0, 0x1e, 0x2b, 0x94, 0x4f, 0x0b, 0xb1, 0x44, 0xea,
	0xf4, 0x9d, 0x81, 0xcb, 0x36, 0x04, 0x21, 0xe0, 0xce, 0xb8, 0x46, 0xba, 0xdb, 0x77, 0x06, 0x75,
	0x66, 0x6a, 0xef, 0x0a, 0x48, 0x5e, 0x46, 0x45, 0x62, 0xa9, 0x90, 0x74, 0xa1, 0x26, 0x51, 0xc5,
	0x81, 0x36, 0x22, 0xfb, 0x2c, 0x43, 0x5e, 0x00, 0xad, 0xb1, 0x58, 0xbe, 0xfb, 0x32, 0xfc, 0xdf,
	0xc4, 0x23, 0xa8, 0x68, 0x3e, 0x37, 0x03, 0x5d, 0x96, 0x94, 0x84, 0xc2, 0x9e, 0x1f, 0xce, 0x1f,
	0x79, 0x88, 0xb4, 0x62, 0x6c, 0x58, 0x98, 0x7c, 0xfb, 0x81, 0x2b, 0xea, 0x1a, 0x36, 0x29, 0xbd,
	0x4b, 0x38, 0x5c, 0x4f, 0xfb, 0xc3, 0xd8, 0x97, 0x03, 0x07, 0xcf, 0x92, 0xcf, 0xd0, 0xfa, 0x3a,
	0x87, 0x66, 0x14, 0xcb, 0xe9, 0x82, 0x2b, 0xcc, 0x7b, 0x2b, 0x92, 0xa4, 0x0f, 0x0d, 0x85, 0x41,
	0x60, 0xfd, 0xa7, 0x3e, 0xf3, 0x14, 0xe9, 0x40, 0x35, 0x92, 0xfe, 0x34, 0x75, 0xeb, 0xb2, 0x14,
	0xd8, 0x5c, 0x6e, 0x69, 0xae, 0x6a, 0x69, 0xae, 0xda, 0x26, 0xd7, 0x05, 0x34, 0x33, 0xaf, 0xbf,
	0xa7, 0x1a, 0xbd, 0x42, 0x6b, 0xb3, 0x9c, 0xe4, 0x04, 0xc8, 0xfd, 0x16, 0x43, 0xd3, 0xb3, 0x18,
	0x6e, 0x1d, 0x43, 0xef, 0xb4, 0xe4, 0x4d, 0x3a, 0xd0, 0xdb, 0x19, 0x3d, 0x40, 0x23, 0xfb, 0xb7,
	0x46, 0xe5, 0xb6, 0x08, 0x4f, 0x6c, 0x6b, 0x61, 0xd9, 0xbd, 0xee, 0x4f, 0x7a, 0x2d, 0x37, 0x81,
	0xba, 0x89, 0x64, 0xba, 0x6f, 0xf2, 0xa0, 0x9d, 0xf5, 0xe4, 0xb7, 0xd3, 0xeb, 0x14, 0x49, 0x2b,
	0xf3, 0x56, 0x33, 0xf4, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xac, 0x49, 0x72, 0xf9,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CreateUserDemoClient is the client API for CreateUserDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreateUserDemoClient interface {
	CreateUserDemo(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type createUserDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateUserDemoClient(cc grpc.ClientConnInterface) CreateUserDemoClient {
	return &createUserDemoClient{cc}
}

func (c *createUserDemoClient) CreateUserDemo(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/proto.CreateUserDemo/CreateUserDemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateUserDemoServer is the server API for CreateUserDemo service.
type CreateUserDemoServer interface {
	CreateUserDemo(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

// UnimplementedCreateUserDemoServer can be embedded to have forward compatible implementations.
type UnimplementedCreateUserDemoServer struct {
}

func (*UnimplementedCreateUserDemoServer) CreateUserDemo(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserDemo not implemented")
}

func RegisterCreateUserDemoServer(s *grpc.Server, srv CreateUserDemoServer) {
	s.RegisterService(&_CreateUserDemo_serviceDesc, srv)
}

func _CreateUserDemo_CreateUserDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateUserDemoServer).CreateUserDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CreateUserDemo/CreateUserDemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateUserDemoServer).CreateUserDemo(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CreateUserDemo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CreateUserDemo",
	HandlerType: (*CreateUserDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserDemo",
			Handler:    _CreateUserDemo_CreateUserDemo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "copyrightDemo.proto",
}

// ConfirmDemoClient is the client API for ConfirmDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfirmDemoClient interface {
	ConfirmDemo(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
}

type confirmDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewConfirmDemoClient(cc grpc.ClientConnInterface) ConfirmDemoClient {
	return &confirmDemoClient{cc}
}

func (c *confirmDemoClient) ConfirmDemo(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, "/proto.ConfirmDemo/ConfirmDemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfirmDemoServer is the server API for ConfirmDemo service.
type ConfirmDemoServer interface {
	ConfirmDemo(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
}

// UnimplementedConfirmDemoServer can be embedded to have forward compatible implementations.
type UnimplementedConfirmDemoServer struct {
}

func (*UnimplementedConfirmDemoServer) ConfirmDemo(ctx context.Context, req *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmDemo not implemented")
}

func RegisterConfirmDemoServer(s *grpc.Server, srv ConfirmDemoServer) {
	s.RegisterService(&_ConfirmDemo_serviceDesc, srv)
}

func _ConfirmDemo_ConfirmDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmDemoServer).ConfirmDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ConfirmDemo/ConfirmDemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmDemoServer).ConfirmDemo(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfirmDemo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ConfirmDemo",
	HandlerType: (*ConfirmDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmDemo",
			Handler:    _ConfirmDemo_ConfirmDemo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "copyrightDemo.proto",
}

// TradeDemoClient is the client API for TradeDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradeDemoClient interface {
	TradeDemo(ctx context.Context, in *TradeRequest, opts ...grpc.CallOption) (*TradeResponse, error)
}

type tradeDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeDemoClient(cc grpc.ClientConnInterface) TradeDemoClient {
	return &tradeDemoClient{cc}
}

func (c *tradeDemoClient) TradeDemo(ctx context.Context, in *TradeRequest, opts ...grpc.CallOption) (*TradeResponse, error) {
	out := new(TradeResponse)
	err := c.cc.Invoke(ctx, "/proto.TradeDemo/TradeDemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeDemoServer is the server API for TradeDemo service.
type TradeDemoServer interface {
	TradeDemo(context.Context, *TradeRequest) (*TradeResponse, error)
}

// UnimplementedTradeDemoServer can be embedded to have forward compatible implementations.
type UnimplementedTradeDemoServer struct {
}

func (*UnimplementedTradeDemoServer) TradeDemo(ctx context.Context, req *TradeRequest) (*TradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeDemo not implemented")
}

func RegisterTradeDemoServer(s *grpc.Server, srv TradeDemoServer) {
	s.RegisterService(&_TradeDemo_serviceDesc, srv)
}

func _TradeDemo_TradeDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeDemoServer).TradeDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TradeDemo/TradeDemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeDemoServer).TradeDemo(ctx, req.(*TradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TradeDemo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TradeDemo",
	HandlerType: (*TradeDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TradeDemo",
			Handler:    _TradeDemo_TradeDemo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "copyrightDemo.proto",
}
